import os
import gc
import math
import json
import argparse
from typing import Dict, List, Tuple, Optional

from tqdm import tqdm
from PIL import Image

import numpy as np
from sklearn.metrics import f1_score

import torch
import torch.nn as nn
from torchvision import transforms
from torchvision.utils import save_image

# ConcatDataset allows merging multiple datasets into one
from torch.utils.data import Dataset, DataLoader, ConcatDataset

# DataLoaders for Fashion MNIST, ResNet classifier initialization and training,
# and U-Net / classifier-free guided vector field for image generation.
from utils import get_dataloaders, save_results
from classification import ClassificationTrainer, create_classifier
from flow import EulerSimulator
from flow.models import IsotropicGaussian, CFGVectorFieldODE, UNet

class SyntheticImageDataset(Dataset):
	"""
	Dataset for loading synthetic images generated by flow matching models.
	"""
	def __init__(self, synthetic_dir: str, transform: Optional[transforms.Compose] = None):
		# synthetic_dir should be e.g., "/content/images/w-3.0" or "/kaggle/working/images/w-3.0"
		self.synthetic_dir = synthetic_dir
		self.transform = transform

		# Store all paths and class labels for synthetic images
		self.image_paths = []
		self.class_labels = []

		# Raise an error if the directory of synthetic images is not found
		if not os.path.exists(synthetic_dir):
			raise FileNotFoundError(f"Synthetic data directory not found: {synthetic_dir}")

		# class_dir should be e.g., "class-83"
		for class_dir in os.listdir(synthetic_dir):
			class_path = os.path.join(synthetic_dir, class_dir)
			if os.path.isdir(class_path):
				cls_label = int(class_dir.split("-")[-1])
				for img_file in os.listdir(class_path):
					if img_file.lower().endswith("png"):
						self.image_paths.append(os.path.join(class_path, img_file))
						self.class_labels.append(cls_label)
		
		# Report the number of images found; should be a multiple of 10.
		print(f"Found {len(self.image_paths)} synthetic images.")

	def __len__(self):
		"""
		Return the number of images found; should be a multiple of 10.
		"""
		return len(self.image_paths)

	def __getitem__(self, idx):
		"""
		Load image at the given index. Class label can be computed as idx //
		samples_per_class, where samples_per_class defaults to 6000.
		"""
		img_path = self.image_paths[idx]
		cls_label = self.class_labels[idx]

		try:
			image = Image.open(img_path).convert("RGB")
			if self.transform:
				image = self.transform(image)
			return image, cls_label
		except Exception as e:
			print(f"Error loading {img_path}: {e}")
			raise

class SyntheticDataGenerator:
	"""
	Generate synthetic data using a pre-trained flow matching model for a given
	guidance scale.
	"""
	def __init__(self, model_path: str, guidance_scale: int):
		self.model_path = model_path
		self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
		self.guidance_scale = guidance_scale
		self.model = None

	def load_model(self):
		self.model = UNet(channels = [32, 64, 128],
						  num_residual_layers = 2,
						  t_embed_dim = 40,
						  y_embed_dim = 40).to(self.device)
		if torch.cuda.device_count() > 1:
			self.model = nn.DataParallel(self.model)

		if os.path.exists(self.model_path):
			state = torch.load(self.model_path, map_location = self.device)
			self.model.load_state_dict(state["model_state_dict"])
			self.model.eval()
		else:
			print(f"Warning: Model parameters not found at {self.model_path}.")

	def denormalize(self, images: torch.Tensor) -> torch.Tensor:
		"""
		Helper function to remove normalization and clamp tensor values to the
		[0, 1] range for one or more images.
		"""
		denorm = transforms.Normalize(mean = [-0.5/0.5],
									  std = [1/0.5])
		images = denorm(images).clamp(0, 1)
		return images
		
	def generate_batch(self, class_label: int, batch_size: int = 32, num_timesteps: int = 100) -> torch.Tensor:
		"""
		Generate a batch of synthetic images for a given class.
		"""
		if self.model is None:
			self.load_model()

		ode = CFGVectorFieldODE(self.model, guidance_scale = self.guidance_scale)
		simulator = EulerSimulator(ode)

		y = torch.full((batch_size, ), class_label, dtype = torch.int64).to(self.device)
		x0, _ = IsotropicGaussian([1, 32, 32]).sample(batch_size)
		x0 = x0.to(self.device)
		ts = torch.linspace(0, 1, num_timesteps).view(1, -1, 1, 1, 1).expand(batch_size, -1, 1, 1, 1).to(self.device)
		x1 = simulator.simulate(x0, ts, y = y)

		# Denormalize and clamp before returning
		return self.denormalize(x1)

	def generate_dataset(self,
						 samples_per_class: int = 6000,
						 generation_batch: int = 6000,
						 num_timesteps: int = 100):
		"""
		Generate a complete synthetic dataset at a given guidance scale.
		"""
		if self.model is None:
			self.load_model()

		num_classes = 10
		ode = CFGVectorFieldODE(self.model, guidance_scale = self.guidance_scale)
		simulator = EulerSimulator(ode)

		for class_label in range(num_classes):
			# Create directory to store the generated images based on the guidance
			# scale and class label
			directory = f"./images/w-{self.guidance_scale}/class-{class_label}"
			os.makedirs(directory, exist_ok = True)

			for batch_id in range(math.ceil(samples_per_class / generation_batch)):
				# Calculate start and end indices for the current batch.
				start_index = batch_id * generation_batch
				end_index = min((batch_id + 1) * generation_batch, samples_per_class)
				num_samples = end_index - start_index

				y = torch.full((num_samples, ), class_label, dtype = torch.int64).to(self.device)

				x0, _ = IsotropicGaussian([1, 32, 32]).sample(num_samples)
				x0 = x0.to(self.device)
				ts = torch.linspace(0, 1, num_timesteps).view(1, -1, 1, 1, 1).expand(num_samples, -1, 1, 1, 1).to(self.device)
				x1 = simulator.simulate(x0, ts, y = y)

				for sample_id in range(start_index, end_index):
					sample = self.denormalize(x1[sample_id - start_index])
					file_name = f"image-{sample_id}_w-{self.guidance_scale}_class-{class_label}.png"
					file_path = os.path.join(directory, file_name)
					save_image(sample, fp = file_path)

				# Delete tensors and clear memory.
				del x0, x1, ts, y
				torch.cuda.empty_cache()
				gc.collect()

class SyntheticAugmentationEvaluator:
	"""
	Evaluate classification performance with synthetic data augmentation.
	"""
	def __init__(self, args, guidance_scale: int):
		self.args = args
		self.guidance_scale = guidance_scale
		self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

	def evaluate_model(self, model: nn.Module, test_loader: DataLoader) -> Dict:
		"""
		Evaluate the performance of a trained ResNet classifier on the Fashion MNIST
		test set, using top-1 accuracy and macro-averaged F1 score (unweighted mean
		of per-class F1, over all classes). The macro-F1 helps reveal systematic un-
		derperformance on individual classes.
		"""
		model.eval()

		correct = 0
		total = 0

		y_true = []
		y_pred = []

		with torch.no_grad():
			for data, target in test_loader:
				data, target = data.to(self.device), target.to(self.device)
				# Compute class logits for each sample in the batch.
				output = model(data)
				# Retrieve model predictions (highest scoring class index),
				# discarding the logits themselves.
				_, prediction = torch.max(output, 1)

				# Append the prediction and ground truth
				y_true.extend(target.cpu().numpy())
				y_pred.extend(prediction.cpu().numpy())

				total += target.size(0)
				# Count the number of correct predictions in the batch.
				correct += (prediction == target).sum().item()

		# Compute the accuracy
		accuracy = 100.0 * correct / total

		# Compute the macro-averaged F1 score
		f1 = f1_score(y_true, y_pred, average = "macro")
		return {"accuracy": accuracy, "f1_macro": f1, "total_samples": total}

	def evaluate_baseline(self, model_path: str, test_loader: DataLoader) -> None:
		"""
		Evaluate the performance of the trained baseline classifier on the Fashion
		MNIST test set, using top-1 accuracy and the macro-averaged F1 score.
		"""
		# Initialize the ResNet classifier, load trained weights, then set it to
		# evaluation mode.
		model = create_classifier(num_classes = 10).to(self.device)
		if torch.cuda.device_count() > 1:
			model = nn.DataParallel(model)
		state = torch.load(model_path, map_location = self.device)
		model.load_state_dict(state["model_state_dict"])

		baseline_evaluation = self.evaluate_model(model, test_loader)
		print(f"Baseline Evaluation: {baseline_evaluation}")

		baseline_eval_path = os.path.join(self.args.classification_dir, "baseline_evaluation.json")
		save_results(baseline_evaluation, baseline_eval_path)

	def run_low_data_experiments(self, real_ratios: List[float] = [0.1, 0.25, 0.5, 1.0]) -> None:
		"""
		Train the ResNet classifier on 10% / 25% / 50% / 100% real + full synthetic
		(equivalent to 100% real trainval) data. Evaluate using top-1 accuracy and
		macro-averaged F1.
		"""
		train_loader, test_loader = get_dataloaders(root_dir = self.args.data_root,
													batch_size = self.args.batch_size,
													num_workers = self.args.num_workers)

		for ratio in real_ratios:
			subdirectory = os.path.join(self.args.augmentation_dir, f"real-{ratio}", f"w-{self.guidance_scale}")
			os.makedirs(subdirectory, exist_ok = True)

			synthetic_dir = os.path.join(self.args.synthetic_data_dir, f"w-{self.guidance_scale}")

			unaugmented_loader = create_augmented_dataset(original_loader = train_loader,
													      synthetic_dir = synthetic_dir,
													      use_synthetic = False,
													      real_ratio = ratio)

			unaugmented_trainer = ClassificationTrainer(self.args)
			unaugmented_results = unaugmented_trainer.train(unaugmented_loader, test_loader)
			unaugmented_evaluation = self.evaluate_model(unaugmented_trainer.model, test_loader)
			
			augmented_loader = create_augmented_dataset(original_loader = train_loader,
														synthetic_dir = synthetic_dir,
														use_synthetic = True,
														real_ratio = ratio)

			augmented_trainer = ClassificationTrainer(self.args)
			augmented_results = augmented_trainer.train(augmented_loader, test_loader)
			augmented_evaluation = self.evaluate_model(augmented_trainer.model, test_loader)

			print(f"Real Data Ratio: {ratio}, Guidance Scale: {self.guidance_scale}")
			print(f"Unaugmented Evaluation: {unaugmented_evaluation}")
			print(f"Augmented Evaluation: {augmented_evaluation}")

			combined_evaluation = {"unaugmented": unaugmented_evaluation, "augmented": augmented_evaluation}
			combined_eval_path = os.path.join(subdirectory, "combined_evaluation.json")
			save_results(combined_evaluation, combined_eval_path)

def create_augmented_dataset(original_loader: DataLoader,
							 synthetic_dir: str,
							 use_synthetic: bool,
							 real_ratio: float = 1.0) -> DataLoader:
	"""
	Combines real data from a DataLoader with synthetic data (if requested) from
	the given directory. Returns a DataLoader which corresponds to the augmented
	dataset.
	"""
	# Retrieve original dataset
	original_dataset = original_loader.dataset

	# Sample the original dataset according to the specified ratio
	if real_ratio < 1.0:
		subset_size = int(len(original_dataset) * real_ratio)
		indices = torch.randperm(len(original_dataset))[:subset_size]
		original_dataset = torch.utils.data.Subset(original_dataset, indices)

	# Create synthetic dataset
	synthetic_dataset = []
	if use_synthetic:
		if not os.path.exists(synthetic_dir):
			raise FileNotFoundError(f"Synthetic data directory not found: {synthetic_dir}")

		reload_transform = transforms.Compose([transforms.Resize(224),
									    	   transforms.RandomHorizontalFlip(),
									    	   transforms.ToTensor(),
									    	   transforms.Lambda(lambda x: x.repeat(3, 1, 1)),
									    	   transforms.Normalize(mean = [0.485, 0.456, 0.406],
														    	   	std = [0.229, 0.224, 0.225])])

		dataset = SyntheticImageDataset(synthetic_dir, transform = reload_transform)
		synthetic_dataset.append(dataset)

	modified_dataset = ConcatDataset([original_dataset] + synthetic_dataset)
	modified_loader = DataLoader(modified_dataset,
						    	 batch_size = original_loader.batch_size,
						    	 shuffle = True,
						    	 num_workers = original_loader.num_workers,
						    	 pin_memory = True,
						    	 persistent_workers = True)
	return modified_loader

def parse_args():
	parser = argparse.ArgumentParser(description = "Evaluation of Synthetic Data Augmentation", add_help = False)

	# Data
	parser.add_argument("--data_root", type = str, default = "./data", help = "Path to Fashion MNIST dataset")
	parser.add_argument("--batch_size", type = int, default = 32, help = "Training batch size")
	parser.add_argument("--num_workers", type = int, default = 2, help = "Number of data loading workers")

	# Training
	parser.add_argument("--epochs", type = int, default = 50, help = "Number of classifier training epochs")
	parser.add_argument("--lr", type = float, default = 0.001, help = "Learning rate")
	parser.add_argument("--weight_decay", type = float, default = 1e-4, help = "Weight decay")
	parser.add_argument("--step_size", type = int, default = 15, help = "Scheduler step size")
	parser.add_argument("--gamma", type = float, default = 0.1, help = "Scheduler gamma")

	# Synthetic data augmentation
	parser.add_argument("--synthetic_data_dir", type = str, default = "./images", help = "Synthetic data directory")
	parser.add_argument("--real_ratio", type = float, default = 1.0, help = "Fraction of real training data to use")

	# Output
	parser.add_argument("--classification_dir", type = str, default = "./results/classification",
				    	help = "Directory for classification results")
	parser.add_argument("--augmentation_dir", type = str, default = "./results/augmentation",
						help = "Directory for augmentation results")
	parser.add_argument("--checkpoint_dir", type = str, default = "./checkpoints",
						help = "Directory for model checkpoints")
	parser.add_argument("--save_interval", type = int, default = 5, help = "Number of epochs between checkpoint saves")

	# General
	parser.add_argument("--seed", type = int, default = 42, help = "Random seed")

	return parser.parse_args()

def main():
	args = parse_args()

	# Create directory to store synthetic augmentation results
	os.makedirs(args.augmentation_dir, exist_ok = True)

	# Set random seed
	torch.manual_seed(args.seed)
	np.random.seed(args.seed)

	# Perform synthetic data evaluation for each guidance scale
	for guidance_scale in (3.0, 5.0, 7.0):
		evaluator = SyntheticAugmentationEvaluator(args, guidance_scale)
		evaluator.run_low_data_experiments()

if __name__ == "__main__":
	main()