import os
import json
import argparse
from typing import Dict, List, Tuple, Optional

import numpy as np
from tqdm import tqdm
from PIL import Image

import torch
import torch.nn as nn
from torchvision import transforms
from torchvision.utils import save_image

# ConcatDataset allows merging multiple datasets into one
from torch.utils.data import Dataset, DataLoader, ConcatDataset

# DataLoaders for FGVC Aircraft, ResNet classifier initialization and training,
# and U-Net / classifier-free guided vector field for image generation.
from utils import get_fgvc_dataloaders
from classification import ClassificationTrainer, create_classifier
from flow import EulerSimulator
from flow.models import IsotropicGaussian, CFGVectorFieldODE, UNet

class SyntheticImageDataset(Dataset):
	"""
	Dataset for loading synthetic images generated by flow matching models.
	"""
    def __init__(self, synthetic_dir: str, transform: Optional[transforms.Compose] = None):
    	# synthetic_dir should be e.g., "/content/images/w-3.0"
        self.synthetic_dir = synthetic_dir
        self.transform = transform

        # Store all paths and class labels for synthetic images
        self.image_paths = []
        self.class_labels = []

        # Raise an error if the directory of synthetic images is not found
	    if not os.path.exists(synthetic_dir):
			raise FileNotFoundError(f"Synthetic data directory not found: {synthetic_dir}")

		# class_dir should be e.g., "class-83"
        for class_dir in os.listdir(synthetic_dir):
			class_path = os.path.join(synthetic_dir, class_dir)
	        if os.path.isdir(class_path):
				cls_label = int(class_dir.split("-")[-1])
                for img_file in os.listdir(class_path):
	                if img_file.lower().endswith("png"):
	                	self.image_paths.append(os.path.join(class_path, img_file))
                        self.class_labels.append(cls_label)
		
		# Report the number of images found; should be a multiple of 100.
	    print(f"Found {len(self.image_paths)} synthetic images.")

    def __len__(self):
    	"""
		Return the number of images found; should be a multiple of 100.
    	"""
        return len(self.image_paths)

    def __getitem__(self, idx):
    	"""
        Load image at the given index. Class label can be computed as idx //
        samples_per_class, where samples_per_class defaults to 67.
    	"""
	    img_path = self.image_paths[idx]
	    cls_label = self.class_labels[idx]
        
        try:
	        image = Image.open(img_path).convert("RGB")
            if self.transform:
	            image = self.transform(image)
            return image, cls_label
	    except Exception as e:
	        print(f"Error loading {img_path}: {e}")
            raise

class SyntheticDataGenerator:
    """
    Generate synthetic data using a pre-trained flow matching model for a given
    guidance scale.
    """
    def __init__(self, model_path: str, guidance_scale: int):
        self.model_path = model_path
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.guidance_scale = guidance_scale
	    self.model = None

	def load_model(self):
		self.model = UNet(channels = [32, 64, 128, 256],
						  num_residual_layers = 2,
						  t_embed_dim = 128,
						  y_embed_dim = 128)

	    if os.path.exists(self.model_path):
            state = torch.load(self.model_path, map_location = self.device)
            self.model.load_state_dict(state["model_state_dict"])
            self.model.to(self.device)
	        self.model.eval()
        else:
		    print(f"Warning: Model parameters not found at {self.model_path}.")

    def denormalize(self, images: torch.Tensor) -> torch.Tensor:
    	"""
    	Helper function to remove ImageNet normalization and clamp tensor values
    	to the [0, 1] range for generated images.
    	"""
    	denorm = transforms.Normalize(mean = [-0.485/0.229, -0.456/0.224, -0.406/0.225],
						    		  std = [1/0.229, 1/0.224, 1/0.225])
    	images = denorm(images).clamp(0, 1)
    	return images

    def generate_batch(self, class_label: int, batch_size: int = 32, num_timesteps: int = 100) -> torch.Tensor:
        """
        Generate a batch of synthetic images for a given class.
        """
        if self.model is None:
	        self.load_model()

        ode = CFGVectorFieldODE(self.model, guidance_scale = self.guidance_scale)
        simulator = EulerSimulator(ode)

        y = torch.tensor([class_label], dtype = torch.int64).repeat_interleave(batch_size).to(self.device)
        x0, _ = IsotropicGaussian([3, 224, 224]).sample(batch_size)
	    ts = torch.linspace(0, 1, num_timesteps).view(1, -1, 1, 1, 1).expand(batch_size, -1, 1, 1, 1).to(self.device)
	    x1 = simulator.simulate(x0, ts, y = y)

	    # Denormalize and clamp before returning
        return self.denormalize(x1)

    def generate_dataset(self, samples_per_class: int = 67, num_timesteps: int = 100):
    	"""
    	Generate a complete synthetic dataset at a given guidance scale.
    	"""
        if self.model is None:
			self.load_model()

    	num_classes = 100
    	ode = CFGVectorFieldODE(self.model, guidance_scale = self.guidance_scale)
	    simulator = EulerSimulator(ode)
	    
	    y = torch.arange(num_classes, dtype = torch.int64).repeat_interleave(samples_per_class).to(self.device)
	    num_samples = y.shape[0]

	    x0, _ = IsotropicGaussian([3, 224, 224]).sample(num_samples)
        ts = torch.linspace(0, 1, num_timesteps).view(1, -1, 1, 1, 1).expand(num_samples, -1, 1, 1, 1).to(self.device)
        x1 = simulator.simulate(x0, ts, y = y)
        x1 = self.denormalize(x1)

		for index in range(num_samples):
			image = x1[index]
			class_label = y[index].item()
			# Create directory to store the generated images based on the guidance
			# scale and class label
			directory = f"/content/images/w-{self.guidance_scale}/class-{class_label}"
			os.makedirs(directory, exist_ok = True)

			file_name = f"image-{index}_w-{w}_class-{class_label:02d}.png"
			file_path = os.path.join(directory, file_name)
			save_image(image, fp = file_path)

class SyntheticAugmentationEvaluator:
    """
    Evaluate classification performance with synthetic data augmentation.
    """
	def __init__(self, base_data_dir: str, results_dir: str):
		self.base_data_dir = base_data_dir
		self.results_dir = results_dir

	def evaluate_baseline(self, model_path: str, test_loader: DataLoader) -> Dict:
		"""
		Evaluate performance of a trained baseline classifier on the FGVC Aircraft
		test set.
		"""
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Initialize the ResNet classifier, load trained weights, then set it to
        # evaluation mode.
        model = create_classifier(num_classes = 100).to(device)
        state = torch.load(model_path, map_location = device)
        model.load_state_dict(state["model_state_dict"])
        model.eval()

        correct = 0
        total = 0

		with torch.no_grad():
			for data, target in test_loader:
				data, target = data.to(device), target.to(device)
				# Compute class logits for each sample in the batch.
				output = model(data)
				# Retrieve model predictions (highest scoring class index),
				# discarding the logits themselves.
				_, prediction = torch.max(output, 1)
				total += target.size(0)
				# Count the number of correct predictions in the batch.
				correct += (prediction == target).sum().item()

        accuracy = 100.0 * correct / total
        return {"accuracy": accuracy, "total_samples": total}

    def run_low_data_experiments(self, real_ratios: List[float] = [0.1, 0.25, 0.5, 1.0]) -> Dict:
		"""
		TODO: Implement training the ResNet on 10% / 25% / 50% / 100% real
		+ full synthetic (equivalent to 100% real trainval) data.
		"""
		raise NotImplementedError("Please implement SyntheticAugmentationEvaluator.run_low_data_experiments.")

    def compare_models(self, synthetic_data_dir: Dict[str, str]) -> Dict:
		"""
		TODO: Implement evaluation of the ResNet trained on different real
		+ synthetic fractions.
		"""
		raise NotImplementedError("Please implement SyntheticAugmentationEvaluator.compare_models.")

def create_augmented_dataset(original_loader: DataLoader,
							 synthetic_dir: str,
							 use_synthetic: bool,
							 real_ratio: float = 1.0) -> DataLoader:
	"""
    Combines real data from a DataLoader with synthetic data (if requested) from
    the given directory. Returns a DataLoader which corresponds to the augmented
    dataset.
	"""
	# Retrieve original dataset
	original_dataset = original_loader.dataset

	# Sample the original dataset according to the specified ratio
	if real_ratio < 1.0:
		subset_size = int(len(original_dataset) * real_ratio)
		indices = torch.randperm(len(original_dataset))[:subset_size]
		original_dataset = torch.utils.data.Subset(original_dataset, indices)

	# Create synthetic dataset
    synthetic_dataset = []
    if use_synthetic:
	    if not os.path.exists(synthetic_dir):
			raise FileNotFoundError(f"Synthetic data directory not found: {synthetic_dir}")

		reload_transform = transforms.Compose([transforms.ToTensor(),
											   transforms.Normalize(mean = [0.485, 0.456, 0.406],
																   	std = [0.229, 0.224, 0.225])])
		dataset = SyntheticImageDataset(synthetic_dir, transform = reload_transform)
		synthetic_dataset.append(dataset)

	modified_dataset = ConcatDataset([original_dataset] + synthetic_dataset)
    modified_loader = DataLoader(modified_dataset,
						    	 batch_size = original_loader.batch_size,
						    	 shuffle = True,
						    	 num_workers = original_loader.num_workers,
						    	 pin_memory = True)
	return modified_loader

def parse_args():
	parser = argparse.ArgumentParser(description = "Evaluation of Synthetic Data Augmentation", add_help = False)

	# Data
	parser.add_argument("--data_root", type = str, default = "/content/data", help = "Path to FGVC Aircraft dataset")
	parser.add_argument("--batch_size", type = int, default = 32, help = "Training batch size")
	parser.add_argument("--num_workers", type = int, default = 2, help = "Number of data loading workers")

	# Training
	parser.add_argument("--epochs", type = int, default = 50, help = "Number of classifier training epochs")
	parser.add_argument("--synthetic_data_dir", type = str, default = None, help = "Synthetic data directory")
    parser.add_argument("--use_synthetic", action = "store_true", help = "Augment training set with synthetic data")
    parser.add_argument("--real_ratio", type = float, default = 1.0, help = "Fraction of real training data to use")

	# Output
	parser.add_argument("--results_dir", type = str, default = "/content/results/augmentation",
						help = "Directory for augmentation results")
	parser.add_argument("--checkpoint_dir", type = str, default = "/content/checkpoints",
						help = "Directory for model checkpoints")

	# Experiments
	parser.add_argument("--run_low_data", action = "store_true", help = "Run low-data experiments")

	return parser.parse_args()

def main():
	args = parse_args()

	# Create directory to store synthetic augmentation results
	os.makedirs(args.results_dir, exist_ok = True)

	# Initialize synthetic data evaluation
	evaluator = SyntheticAugmentationEvaluator(args.data_root, args.results_dir)

	if args.run_low_data:
		evaluator.run_low_data_experiments()

if __name__ == "__main__":
	main()